#!/bin/sh

exec socat UNIX-LISTEN:/home/<your-username>/.gnupg/S.gpg-agent,fork, EXEC:'npiperelay.exe --input-closes --pipe-closes --gpg "C:/Users/<your-user-folder>/AppData/Roaming/gnupg/S.gpg-agent"',nofork
